### ISSUE TITLE
Some minor improvements

### ISSUE THREAD

**Issue by ColdAndMiserable** [clamchowder/MicrobenchmarksGui#1]
1. Remove add rax,r15 from "latencytest". This operation serves no purpose.
2. Add vzeroupper to the end AVX functions.
3. Change 64-bit counter to 32-bit counter to save 1-byte.
4. Do not use QueryPerformanceCounter.
That is all for now.

**Comment by clamchowder** [comment]
1. That's to make it consistent with the C version, where I sum up the results to prevent the compiler from optimizing out the pointer chasing. It should not affect anything unless you had a scalar in-order pipeline and single cycle L1D latency. No remotely modern x86 CPU has that.
2. Sure, I'll get around to it at some point. Been very busy
3. Which counter?
4. Where's QueryPerformanceCounter used?

**Comment by ColdAndMiserable** [comment]
3. There was a 64-bit counter in there somewhere.
4. It was in the list of windows functions. There's no other direct means to get the RDTSC frequency for AMD other than measuring it using the real-time clock over a long period.

**Comment by clamchowder** [comment]
Can you be more specific? Feel free to open a pull request

**Comment by ColdAndMiserable** [comment]
e.g. "avx_asm_read" uses a 64-bit counter when 32-bit should be fine.

I can't even find any timers anywhere in the code. It must be hidden inside the C#.
rdtsc called directly is best.

**Comment by clamchowder** [comment]
Ah, the loop counters for that? They're stored in registers, so using 64-bit vs 32-bit doesn't make any difference. The register itself is 64 bits wide, and say, using esi vs rsi would not make things go any faster.

If C# internally uses QueryPerformanceCounter somewhere, that's not something I have control over. I don't do any timing from within C# anyway. I'm using C timing APIs for simplicity. The tests should run for long enough that more precise timing would not be needed.

Feel free to fork and make changes, or open a pull request if you feel changes are needed.
